# Generated by Django 4.1.7 on 2023-04-06 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authenticate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bms_bulding_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bms_department_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bms_sub_area_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_area_name', models.CharField(max_length=100)),
                ('on_image_path', models.CharField(max_length=255)),
                ('off_image_path', models.CharField(max_length=255)),
                ('width', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('seating_capacity', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('department_id', models.ManyToManyField(blank=True, to='Device.bms_department_master')),
            ],
        ),
        migrations.CreateModel(
            name='Bms_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module_id', models.ManyToManyField(blank=True, to='Authenticate.bms_module_master')),
            ],
        ),
        migrations.CreateModel(
            name='Bms_locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locker_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('N', 'Normal'), ('B', 'Big')], max_length=100)),
                ('status', models.CharField(choices=[('A', 'Active'), ('N', 'Inactive')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('sub_area_id', models.ManyToManyField(blank=True, to='Device.bms_sub_area_master')),
            ],
        ),
        migrations.CreateModel(
            name='Bms_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('N', 'Newuser'), ('V', 'Visitor'), ('A', 'Access'), ('C', 'Conference')], max_length=100)),
                ('description', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ManyToManyField(blank=True, to='Authenticate.bms_users')),
            ],
        ),
        migrations.CreateModel(
            name='Bms_floor_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('tower_id', models.ManyToManyField(blank=True, to='Device.bms_bulding_master')),
            ],
        ),
        migrations.AddField(
            model_name='bms_department_master',
            name='floor_id',
            field=models.ManyToManyField(blank=True, to='Device.bms_floor_master'),
        ),
        migrations.CreateModel(
            name='Bms_access_control_rfid_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_no', models.IntegerField()),
                ('card_type', models.CharField(choices=[('N', 'No-assign'), ('S', 'Static'), ('D', 'Dynamic')], max_length=100)),
                ('status', models.CharField(choices=[('A', 'Active'), ('N', 'Inactive')], max_length=100)),
                ('access_start_time', models.DateField(default=django.utils.timezone.now)),
                ('access_end_time', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('access_area_id', models.ManyToManyField(blank=True, to='Device.bms_sub_area_master')),
                ('user_id', models.ManyToManyField(to='Authenticate.bms_users')),
            ],
        ),
    ]
